/** Discovered direct ASP.NET paths from authenticated admin home sidebar */
export const ADMIN_DIRECT_URLS: Record<string, string> = {
  // Wave 1
  master_bank: '/master/BankDetails.aspx',
  bp_list: '/membermanagement/AdminMemberList.aspx',
  sale_list: '/sales/BookingPlotList.aspx',
  accounting_transactions: '/accountingoperation/transactions.aspx',
  neft_list: '/memberpayout/NEFTList.aspx',
  // Accounts Operation
  bp_payment: '/accountingoperation/EntityList.aspx?id=19',
  business_promotion: '/accountingoperation/EntityList.aspx?id=3083',
  director_payment: '/accountingoperation/EntityList.aspx?id=2060',
  fee_and_charges: '/accountingoperation/EntityList.aspx?id=3085',
  investor: '/accountingoperation/EntityList.aspx?id=17',
  land_expense: '/accountingoperation/EntityList.aspx?id=1',
  loan_advances: '/accountingoperation/EntityList.aspx?id=2057',
  monthly_expense: '/accountingoperation/EntityList.aspx?id=3103',
  office_expense: '/accountingoperation/EntityList.aspx?id=7',
  selling_distribution: '/accountingoperation/EntityList.aspx?id=3086',
  site_visit: '/accountingoperation/EntityList.aspx?id=3',
  tax_consultancy: '/accountingoperation/EntityList.aspx?id=3084',
  accounts_daily_summary: '/accountingoperation/DailyTransactionSummary.aspx',
  // Sale Operation
  new_sale: '/sales/BookingAdd.aspx',
  add_earning_on_sale: '/sales/BookingDepositAdd.aspx',
  sale_transactions: '/sales/BookingDepositeList.aspx',
  hold_for_sale: '/sales/BookingPlotListHold.aspx',
  sale_daily_summary: '/sales/DailySalesReport.aspx',
  sale_attachments: '/sales/SaleAttachments.aspx',
  // Accounts Reports
  accounts_daily_report: '/accountingreports/DailyTransactions.aspx',
  transactions_sheet: '/accountingreports/Transactions_Sheet.aspx',
  accounts_monthly_report: '/accountingreports/MonthlyTransactions.aspx',
  accounts_yearly_report: '/accountingreports/YearlyTransactions.aspx',
  // Administrator
  users: '/admin/UserList.aspx',
  control_group: '/admin/AuthGroup.aspx',
  control_page: '/admin/AuthPage.aspx',
  company: '/admin/Company.aspx',
  accounting_trans_log: '/admin/AccVoucherList_log.aspx',
  full_monthly_summary: '/admin/FullMonthlySummary.aspx',
  // Banking
  bank_to_bank: '/banking/BankToBankADD.aspx',
  cash_ledger: '/banking/CashLedger.aspx',
  sale_cheques: '/banking/SaleChequesList.aspx',
  accounting_cheques: '/banking/AccountingChequesList.aspx',
  // BP Management
  monthly_sale_point: '/membermanagement/ProjectWiseMonthPoint.aspx',
  bp_income_summary: '/membermanagement/IncomeSummary.aspx',
  bp_payout_mgmt: '/membermanagement/PayoutGeneration.aspx',
  bp_award_achieved: '/membermanagement/RewardAchieved.aspx',
  new_bp: '/membermanagement/AddNewBP.aspx',
  bp_bulk_payment: '/membermanagement/BPBulkPayment.aspx',
  bp_income_summary_detail: '/membermanagement/BPIncomeSummary.aspx',
  bp_income_reward_emi: '/membermanagement/BPIncomeRewardEMI.aspx',
  income_by_sale_earning: '/membermanagement/BPIncomeSaleEarning.aspx',
  bp_sale_performance: '/membermanagement/BPSalePerformance.aspx',
  bp_summary_fin_year: '/membermanagement/BPSummaryFinYear.aspx',
  bp_award_shares: '/membermanagement/RewardAchievedShares.aspx',
  site_visit_expense: '/membermanagement/BPSiteVisitExpense.aspx',
  // BP Payout
  income_details: '/memberpayout/IncomeDetails.aspx',
  downline_income_summary: '/memberpayout/MemberDownlineIncomeSummary.aspx',
  bp_income_details: '/memberpayout/MemberIncomeDetails.aspx',
  payout_balance_sheet: '/memberpayout/MemberPendingIncomeSummary.aspx',
  neft_list_reward_emi: '/memberpayout/NEFTListEMI.aspx',
  reward_emi_reward_wise: '/memberpayout/NEFTListEMIReward.aspx',
  payout_income_summary: '/memberpayout/PayoutSummary.aspx',
  reward_booking_details: '/memberpayout/RewardDetails.aspx',
  reward_emi_details: '/memberpayout/RewardEMIIncome.aspx',
  reward_emi_not_achieved: '/memberpayout/RewardEMINotAchieve.aspx',
  neft_list_reward: '/memberpayout/RewardNeftDetails.aspx',
  reward_setting: '/memberpayout/RewardSetting.aspx',
  // Finder & Editor
  finder_accounting_transactions: '/findereditor/AccVoucherEditor.aspx',
  accounting_entity: '/findereditor/AccEntityEditor.aspx',
  finder_sales_transaction: '/findereditor/SaleTransactionEditor.aspx',
  finder_sales: '/findereditor/SaleListEditor.aspx',
  // Joining Pin
  epin_list: '/joiningpin/AdminMemberEPinStockSummary.aspx',
  pin_generator_transfer: '/joiningpin/AdminPinGenerateNTransfer.aspx',
  transfer_epin: '/joiningpin/AdminTransferPin.aspx',
  epin_request_details: '/joiningpin/PinRequestDetails.aspx',
  // Master
  project_phase: '/master/ProjectPhase.aspx',
  project: '/master/ProjectMain.aspx',
  branch: '/master/Branch.aspx',
  accounting_head: '/master/AccountingHead.aspx',
  // Raw Management
  registry_list: '/rawassets/BookingPlotListRegistry.aspx',
  govt_survey_plot: '/rawassets/PlotGovtSurveyList.aspx',
  plot_list: '/rawassets/PlotList.aspx',
  registered_plot_list: '/rawassets/RegisteredPlotList.aspx',
  raw_land_broker: '/rawassets/RawLandBroker.aspx',
  raw_land_owner: '/rawassets/RawLandOwner.aspx',
  raw_land: '/rawassets/RawLand.aspx',
  raw_payments: '/rawassets/RawPaymentList.aspx',
  // Sale Report
  booking_performance: '/salesreport/BookingPerformance.aspx',
  sale_report_daily: '/salesreport/DailySalesReport.aspx',
  sale_report_monthly: '/salesreport/MonthlySalesReport.aspx',
  sale_report_yearly: '/salesreport/YearlySalesReport.aspx',
  sale_report_transactions: '/salesreport/SalesTransactions_Sheet.aspx',
  sales_performance_report: '/salesreport/SalesPerformanceReport.aspx',
  sales_accounts_report: '/salesreport/SalesAccountingReport.aspx',
};

export function resolveAdminDirectUrl(key: string): string | undefined {
  return ADMIN_DIRECT_URLS[key];
}
